language: go
sudo: false
go:
  - 1.9
  - tip

before_install:
  - go get github.com/jteeuwen/go-bindata/...
  - go generate

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
