# config.toml
################################################################
# Global
################################################################

# Port
# Reserved for web API interface
port = ":9090"

# Log level
# log_level = "warning"

# Secret key
# Is passed along with every request to that site in the X-Go-Sleep-Key header
# secret_key = ""

# Group user for basic auth
# Passwords can be encoded in MD5, SHA1 and BCrypt: you can use htpasswd to generate those ones

# [auth]
#  [auth.<group_name>]
#    users = ["<user>:<password>", "<user>:<password>"]


################################################################
# Google Cloud Engine
################################################################

# [[gce]]
# jwt_path = "/path/to/key_jwt.json"
# project_id = "project-id>"
# zone = "europe"
# name = "name"
# use_internal_ip = false  # if set true, go-sleep will use the internal IP, default false
# sleep_after = 1200  # after N seconds of inactivity, the server will be turned off, default 1200
#  [[gce.route]]
#  address = ":80" # Default :80
#  hostnames = ["<hostname.local>"]
#  auth_group = "<group_name>"  # if set, enabled basic auth
#  backend_port = 80  # if not set, use value from "address" option
#    [[gce.route.certificate]]  # if set, enable TLS
#    cert_file = "/path/to/server.crt"
#    key_file = "/path/to/server.key"


################################################################
# Amazon EC2
################################################################

# [[ec2]]
# access_key_id = "KEY_ID"
# secret_access_key = "ACCESS_KEY"
# region = "us-west"
# instance_id = "instance-00"
# use_internal_ip = false  # if set true, go-sleep will use the internal IP, default false
# sleep_after = 1200  # After N seconds of inactivity, the server will be turned off, default 1200
#  [[gce.route]]
#  address = ":80" # Default :80
#  hostnames = ["<hostname.local>"]
#  auth_group = "<group_name>"  # if set, enabled basic auth
#  backend_port = 80  # if not set, use value from "address" option
#    [[gce.route.certificate]]  # if set, enable TLS
#    cert_file = "/path/to/server.crt"
#    key_file = "/path/to/server.key"
